### ISSUE TITLE
Colab Notebook

### ISSUE THREAD

**Issue by mrm8488** [nicklashansen/policy-adaptation-during-deployment#1]
Hi, I think a Colab Notebook would help to get into it.
Nice work!

**Comment by nicklashansen** [comment]
Hi,
Thank you for your interest. Our experiments are based on the proprietary MuJoCo physics simulator (you can obtain trial licenses and student licenses for free on their website), which unfortunately makes it hard if not impossible to run our benchmarks on Colab as is; see https://github.com/openai/mujoco-py/issues/358 and https://github.com/openai/mujoco-py/issues/416 for reference. We would be happy to release a Colab notebook if these circumstances change in the future!

**Comment by rrustagi20** [comment]
- - - - - - #         ~~ ~~
