### ISSUE TITLE
Robot Experiments

### ISSUE THREAD

**Issue by chongyi-zheng** [nicklashansen/policy-adaptation-during-deployment#2]
Hello, there. This work is simple but impressive! I saw a robot experiment in the paper and want to try it. So does the mujoco environment for the robot experiment contains in this repo, or it is possible to run this algorithm with some popular robot benchmark?

By the way, I have another question about the difference between the simulated and real robot. Does simulation match the default transfer setting in figure 6 of the paper exactly, i.e. box size, friction, and mass, without ablating these variables?

**Comment by nicklashansen** [comment]
Thank you! The robotic manipulation environment is not included in the repo. We are working on open-sourcing that environment but I currently do not have a time estimate.

The simulation is only built to approximately replicate the real robot setup. We have not made any serious attempt to match the robot controls, object dimensions, camera pose etc, which poses an interesting sim2real experimental setup as directly transferring a policy without adaptation often fails in this setting.

**Comment by chongyi-zheng** [comment]
Thanks for your feedback. And hope the robot experiment will be available soon. 

I have another question about DMC experiments when I try it myself. Did you try environments other than the three ones in the paper? I found the image input SAC algorithm cannot let the Ant agent running in the Empty corridor (this task is under the locomotion suite), is it because the task is too difficult or simply the input viewpoint is unstable? (I saw the evaluation video and the camera kept rotating and moving up and down while tracking the Ant.)

**Comment by nicklashansen** [comment]
SAC does not solve all of the tasks available in DMC from image inputs. Since we are mostly interested in measuring the generalization of algorithms in our experiments, we simply picked 9 tasks that have been solved in previous work.

**Comment by chongyi-zheng** [comment]
Okay, got it. Sorry for not reading the experiment part of the paper carefully. I see there are nine tasks in table 1 of the paper. And now an update of the experiment above is available since I raise the question before checking the result for a whole night running: 

The SAC with image input is able to train an Ant to run the corridor if you train it for enough steps, i. e. 50K (with a poor performance for the first 25K). So the performance is simply related to sample efficiency.

Minor point: Around 24 hours is needed to train the PAD algorithm for 50K which is much slower than the vector input version SAC.

**Comment by nicklashansen** [comment]
No problem, great to hear that you solved it! And yes, unfortunately image-based RL is significantly slower than state-based.
