### ISSUE TITLE
Questions about: replicating results of SAC+DR

### ISSUE THREAD

**Issue by gemcollector** [nicklashansen/policy-adaptation-during-deployment#5]
Hello! I wanna ask how to replicate results of SAC+DR？And what's the difference between color-easy and color hard，does it mean random color setting?

**Comment by nicklashansen** [comment]
Hi -- correct, color-easy and color-hard are two random color distributions, easy and hard difficulties, respectively. color-hard is used for evaluation and the SAC+DR baseline is trained on color-easy as we found directly training on color-hard too difficult. So simply training the SAC baseline on color-easy and evaluating on color-hard should reproduce our results. And just as a heads-up: our other repository [DMControl Generalization Benchmark](https://github.com/nicklashansen/dmcontrol-generalization-benchmark) contains additional implementations and results, which may or may not be relevant to you. I will keep this issue open for a bit in case you have additional questions.

**Comment by gemcollector** [comment]
> Hi -- correct, color-easy and color-hard are two random color distributions, easy and hard difficulties, respectively. color-hard is used for evaluation and the SAC+DR baseline is trained on color-easy as we found directly training on color-hard too difficult. So simply training the SAC baseline on color-easy and evaluating on color-hard should reproduce our results. And just as a heads-up: our other repository [DMControl Generalization Benchmark](https://github.com/nicklashansen/dmcontrol-generalization-benchmark) contains additional implementations and results, which may or may not be relevant to you. I will keep this issue open for a bit in case you have additional questions.



> Hi -- correct, color-easy and color-hard are two random color distributions, easy and hard difficulties, respectively. color-hard is used for evaluation and the SAC+DR baseline is trained on color-easy as we found directly training on color-hard too difficult. So simply training the SAC baseline on color-easy and evaluating on color-hard should reproduce our results. And just as a heads-up: our other repository [DMControl Generalization Benchmark](https://github.com/nicklashansen/dmcontrol-generalization-benchmark) contains additional implementations and results, which may or may not be relevant to you. I will keep this issue open for a bit in case you have additional questions.

Thanks for your answering ! I still got a question about robotic manipulation tasks you mentioned in this paper: Stabilizing Deep Q-Learning with ConvNets and Vision Transformers under Data Augmentation. Can we use this robotic benchmark? If we can, how can we set up it ? Thx～！

**Comment by nicklashansen** [comment]
Hi, the robotic benchmark is not publicly available at this time, but you should be able to largely reproduce the environments and tasks by using e.g. the OpenAI Gym Fetch code as a starting point and modifying that.
