### ISSUE TITLE
CRLMaze experimental set-up

### ISSUE THREAD

**Issue by PhiCtl** [nicklashansen/policy-adaptation-during-deployment#7]
Hello,
Thanks a lot for your very inspiring and clearly-presented work ! 
Following your paper, I've seen you've made some experiments with CRLMaze environment. I'd like to know if you were to release some of your code examples regarding those experiments ? I'd be very interested !

Many thanks !

**Comment by nicklashansen** [comment]
Hi! Glad to hear that you're interested in our work. Unfortunately the CRLMaze environments have not been released, but it should be possible to reproduce our results using the CRLMaze repository as a starting point and adding test environments + PAD on top following the implementation details of our paper.

I am closing this issue for now but feel free to reopen if you have any follow-up questions!

Best,
