### ISSUE TITLE
How to use distractor environment with your code

### ISSUE THREAD

**Issue by MaryAhn** [nicklashansen/policy-adaptation-during-deployment#8]
Hi, I want to run your code with distractor in your paper. (distracting control suite)
How can I use it in your code?
Thanks:)

**Comment by nicklashansen** [comment]
Hi, unfortunately the distractor environments have not been released, only color + video. However, it should be possible to reproduce our distractor experiments by modifying the dm_control mujoco files to include a red sphere in the background. We also open-sourced a more comprehensive test suite over at https://github.com/nicklashansen/dmcontrol-generalization-benchmark which you may or may not find useful.

I am closing this issue for now but feel free to reopen if you have any follow-up questions!

Best,
